codex_experiment:
  experiment_set_id: ${EXPERIMENT_SET_ID}
  seeder_sets: ${SEEDER_SETS}
  seeders: ${SEEDERS}
  file_size: ${FILE_SIZE}
  repetitions: ${REPETITIONS}
  # Should we delete the data at the end of each experiment (slower, uses less space), or we just
  # leave it there (faster, uses more space)?
  remove_data: ${REMOVE_DATA}
  # No need for cooldown as Codex takes forever to remove files, so there's plenty of time to log stuff. :-)
  logging_cooldown: 0
  stagger_delay: ${STAGGER_DELAY}

  nodes:
    network_size: ${NETWORK_SIZE}
    first_node_index: 0
    name: "${CODEX_STATEFULSET}-{node_index}"
    address: "${CODEX_STATEFULSET}-{node_index}.${CODEX_SERVICE}.${NAMESPACE}.svc.cluster.local"
    disc_port: 6890
    api_port: 6891
    agent_url: "http://${CODEX_STATEFULSET}-{node_index}.${CODEX_SERVICE}.${NAMESPACE}.svc.cluster.local:9001/"
